name: Trigger External Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger_external_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: manasachi/azure-provider-external-dns-e2e
          ref: main

      - name: Trigger External Workflow
        uses: passeidireto/trigger-external-workflow-action@main
        with:
          workflow: .github/workflows/e2ev2-provision-test.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
